### ISSUE TITLE
New York Times Search

### ISSUE THREAD

**Issue by Lomontrandsabert** [Lomontrandsabert/New-NYTimes#1]
My app is complete, please review. /cc @codepathreview @codepath

https://github.com/Lomontrandsabert/New-NYTimes
I try upload the zipped file but its to big. so please check the link you'll see may work.

Thanks!

![nytimessearch](https://user-images.githubusercontent.com/30005382/28760376-b9467a6c-7574-11e7-8211-0613e4cccf97.gif)

[README.txt](https://github.com/Lomontrandsabert/New-NYTimes/files/1186222/README.txt)

**Comment by codepathreview** [comment]
Consider trying out the RecyclerView, the successor to the ListView and GridView.

**Comment by codepathreview** [comment]
Consider adding the ability to share a news article. This is an important learning for this assignment even though it's optional.
